# MYSQL DATABASE CONFIGURATION
spring.application.name=bank_menu
spring.datasource.url=jdbc:mysql://localhost:3306/bank_account
spring.datasource.username=root
spring.datasource.password=Br@ve12Heart
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RABBITMQ MESSAGE BROKER CONFIGURATION
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest